### ISSUE TITLE
Only add template if folder is empty or does not exist

### ISSUE THREAD

**Issue by lurilandi** [aarhusstadsarkiv/TemplateHandler#7]
# The problem
When there are multiple copies of a Lotus Nodes file, it happens that Symphovert cannot convert all copies of the file since the convert process is very unstable (i.e. a somewhat problematic file between the copies can break the pyautogui flow). In this case, Templatehandler will insert a template for all of the copies (because they have the same checksum) even though some of them have been converted.

# Solution
TemplateHandler should only load the files with the given checksum where the uuid is not in _ConvertedFiles. This requires that the  _ConvertedFiles is also parsed as objects in memory with the Entity framework.

**Comment by clausjuhl** [comment]
Fixed in latest pr
